// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkucwdydkbujvkuotbms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdWN3ZHlka2J1anZrdW90Ym1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDMyNDcsImV4cCI6MjA1ODAxOTI0N30.z1t9BS3htXimWLiC8lYXCwFaP0kPcBxCaylf4L2NeMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);